ARG BASE_TAG
FROM ${BASE_TAG}
ARG DEBIAN_FRONTEND=noninteractive
COPY packages.txt .
COPY requirements.txt .
COPY postinstallscript.sh .
RUN apt-get update && apt-get install -y $(cat packages.txt)
RUN pip install --no-cache-dir -r requirements.txt
RUN bash postinstallscript.sh
WORKDIR /workspace
